import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Home, Compass, Music2, Clapperboard, Mic2, Users, ShoppingBag, Library, Settings, UserRound, Search, Bell, Play, Pause, Heart, MoreHorizontal, Plus, ArrowRight, ChevronRight, Headphones, Download, Upload, BarChart3, DollarSign, Menu, X, ShieldCheck, Sparkles, Save, FileAudio, Image, Check} from 'lucide-react';
import './styles.css';
import './screens.css';
import {auth, db, googleProvider} from './lib/firebase';
import {createUserWithEmailAndPassword, onAuthStateChanged, signInWithEmailAndPassword, signInWithPopup, signOut, updateProfile} from 'firebase/auth';
import {ensureProfile} from './lib/profile';
import logo from '../../asset/infini_logo_blanc.svg';

const artists=[
 {name:'Ekenge Musique', genre:'Musique · RDC', img:'/artists/ekenge.jpeg'},
 {name:'Gigi Légendaire', genre:'Artiste · RDC', img:'/artists/gigi-legendaire.jpeg'},
 {name:"Jock'Afrique", genre:'Artiste · RDC', img:'/artists/jock-afrique.png'},
 {name:'Khali Swaga', genre:'Musique · RDC', img:'/artists/khali-swaga.jpeg'},
 {name:'Nathma', genre:'Artiste · RDC', img:'/artists/nathma.jpeg'},
 {name:'Star Gondo', genre:'Artiste · RDC', img:'/artists/star-gondo.jpeg'},
 {name:'T.I Zoo', genre:'Artiste · RDC', img:'/artists/ti-zoo.jpeg'},
 {name:'TPS One', genre:'Artiste · RDC', img:'/artists/tps-one.jpeg'}
];
const tracks=[
 {title:'Nzela', artist:'Ekenge Musique', album:'Ekenge', cover:'/artists/ekenge.jpeg', plays:'82K', time:'3:42'},
 {title:'Loboko', artist:'Gigi Légendaire', album:'Légendaire', cover:'/artists/gigi-legendaire.jpeg', plays:'64K', time:'4:18'},
 {title:'Kinshasa la nuit', artist:"Jock'Afrique", album:"Jock'Afrique", cover:'/artists/jock-afrique.png', plays:'51K', time:'3:07'},
 {title:'Soki yo te', artist:'Khali Swaga', album:'Swaga', cover:'/artists/khali-swaga.jpeg', plays:'43K', time:'3:55'}
];
const products=[
 {name:'Mokili — Album complet', artist:'Jérémie Kanda', type:'Album digital', price:'7,00 $', cover:tracks[0].cover},
 {name:'Live à la Halle de la Gombe', artist:'Sista Becky', type:'Performance vidéo', price:'4,50 $', cover:'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=700&q=85'},
 {name:'Lumière sur le fleuve', artist:'Kiese', type:'Photographie numérique', price:'12,00 $', cover:'https://images.unsplash.com/photo-1531058020387-3be344556be6?auto=format&fit=crop&w=700&q=85'}
];

function BrandLogo({className=''}){return <span className={`brand-lockup ${className}`} style={{display:'flex',alignItems:'center',gap:9}}><img className="brand-logo" src={logo} alt="" style={{display:'block',width:38,height:38,objectFit:'contain'}}/><span style={{fontSize:18,fontWeight:800,letterSpacing:'-0.8px',whiteSpace:'nowrap'}}>infini record</span></span>}

function App(){
 const [page,setPage]=useState('home'); const [playing,setPlaying]=useState(null); const [liked,setLiked]=useState([]); const [cart,setCart]=useState([]); const [mobile,setMobile]=useState(false); const [user,setUser]=useState(null); const [authOpen,setAuthOpen]=useState(false); const [query,setQuery]=useState('');
 useEffect(()=>onAuthStateChanged(auth,(nextUser)=>{setUser(nextUser); if(nextUser) ensureProfile(nextUser).catch(console.error)}),[]);
 const nav=[['home','Accueil',Home],['discover','Découvrir',Compass],['music','Musique',Music2],['videos','Vidéos',Clapperboard],['performances','Performances',Mic2],['artists','Artistes',Users],['store','Boutique',ShoppingBag],['library','Bibliothèque',Library]];
 const go=(p)=>{setPage(p);setMobile(false)};
 const screen = query.trim() ? <SearchPage query={query} go={go} playing={playing} setPlaying={setPlaying} /> : page==='settings' ? <SettingsPage/> : page==='upload' ? <UploadPage go={go}/> : page==='home'?<HomePage go={go} playing={playing} setPlaying={setPlaying} liked={liked} setLiked={setLiked} />:page==='artist'?<ArtistDashboard go={go}/>:page==='cart'?<Cart cart={cart} setCart={setCart} go={go}/>:page==='library'?<LibraryPage go={go}/>:<Collection page={page} go={go} playing={playing} setPlaying={setPlaying} add={(p)=>setCart([...cart,p])} />;
 return <div className="app">
  <aside className={mobile?'sidebar open':'sidebar'}><div className="brand" onClick={()=>go('home')}><BrandLogo/></div><div className="nav-label">Explorer</div><nav>{nav.map(([id,label,Icon])=><button className={page===id?'nav-item active':'nav-item'} onClick={()=>go(id)} key={id}><Icon size={18}/><span>{label}</span>{id==='store'&&<i className="dot"/>}</button>)}</nav><div className="sidebar-bottom"><div className="nav-label">Espace personnel</div><button className="nav-item" onClick={()=>go('artist')}><Sparkles size={18}/><span>Espace artiste</span></button><button className="nav-item" onClick={()=>go('settings')}><Settings size={18}/><span>Paramètres</span></button><div className="user-mini"><img src={artists[1].img}/><div><b>Junior M.</b><small>Membre depuis 2024</small></div><MoreHorizontal size={17}/></div></div></aside>
  <main className="main"><header><button className="mobile-menu" onClick={()=>setMobile(!mobile)}>{mobile?<X/>:<Menu/>}</button><div className="search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher un artiste, une œuvre..."/><span>⌘ K</span></div><div className="head-actions"><button className="icon-btn"><Bell size={19}/><i/></button><button className="cart-btn" onClick={()=>go('cart')}><ShoppingBag size={18}/>{cart.length>0&&<b>{cart.length}</b>}</button>{user?<button className="profile-pill" onClick={()=>signOut(auth)}><img src={user.photoURL||artists[1].img}/><span>{user.displayName||user.email?.split('@')[0]}</span><ChevronRight size={15}/></button>:<button className="profile-pill" onClick={()=>setAuthOpen(true)}><UserRound size={17}/><span>Se connecter</span></button>}</div></header><div className="content">{screen}</div></main>
  {playing&&<Player track={playing} setPlaying={setPlaying}/>}<div className="bottom-nav">{nav.slice(0,5).map(([id,label,Icon])=><button onClick={()=>go(id)} className={page===id?'selected':''} key={id}><Icon size={20}/><small>{label}</small></button>)}</div>{authOpen&&<AuthModal close={()=>setAuthOpen(false)}/>} 
 </div>
}
function AuthModal({close}){const [mode,setMode]=useState('login');const [role,setRole]=useState('fan');const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [name,setName]=useState('');const [error,setError]=useState('');const [loading,setLoading]=useState(false);const submit=async(e)=>{e.preventDefault();setLoading(true);setError('');try{let credential;if(mode==='login') credential=await signInWithEmailAndPassword(auth,email,password);else{credential=await createUserWithEmailAndPassword(auth,email,password);await updateProfile(credential.user,{displayName:name});await ensureProfile({...credential.user,displayName:name},role)}close()}catch(err){setError(err.code==='auth/invalid-credential'?'Email ou mot de passe incorrect.':err.code==='auth/email-already-in-use'?'Cet email est déjà utilisé.':'Vérifie les informations saisies.')}finally{setLoading(false)}};return <div className="modal-backdrop" onClick={close}><div className="auth-modal" onClick={e=>e.stopPropagation()}><button className="modal-close" onClick={close}><X size={18}/></button><div className="brand modal-brand"><BrandLogo/></div><span className="kicker">{mode==='login'?'BIENVENUE À NOUVEAU':'REJOINDRE INFINI RECORD'}</span><h2>{mode==='login'?'Se connecter':'Créer un compte'}</h2><p>{mode==='login'?'Retrouvez votre univers musical.':'Découvrez et soutenez les talents africains.'}</p>{mode==='register'&&<div className="role-switch"><button className={role==='fan'?'selected':''} onClick={()=>setRole('fan')}>Je suis un fan</button><button className={role==='artist'?'selected':''} onClick={()=>setRole('artist')}>Je suis artiste</button></div>}<form onSubmit={submit}>{mode==='register'&&<input required value={name} onChange={e=>setName(e.target.value)} placeholder={role==='artist'?'Nom artistique':'Votre nom'}/>}<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Adresse email"/><input required minLength="6" type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mot de passe"/>{error&&<small className="form-error">{error}</small>}<button className="primary auth-submit" disabled={loading}>{loading?'Patientez...':mode==='login'?'Se connecter':'Créer mon compte'}</button></form><button className="google-btn" onClick={async()=>{try{const credential=await signInWithPopup(auth,googleProvider);await ensureProfile(credential.user,role);close()}catch(e){setError('Connexion Google indisponible.')}}}>Continuer avec Google</button><button className="switch-auth" onClick={()=>setMode(mode==='login'?'register':'login')}>{mode==='login'?"Je n'ai pas encore de compte":"J'ai déjà un compte"}</button></div></div>}
function HomePage({go,playing,setPlaying,liked,setLiked}){return <>
 <section className="hero"><div className="hero-copy"><div className="eyebrow"><span/> ÉDITION KINSHASA <span/></div><h1>L'art congolais<br/><em>n'a pas de limite.</em></h1><p>Découvrez les voix, les histoires et les talents qui font vibrer l'Afrique.</p><div className="hero-actions"><button className="primary" onClick={()=>go('discover')}>Découvrir maintenant <ArrowRight size={16}/></button><button className="ghost" onClick={()=>go('artist')}>Devenir artiste</button></div></div><div className="hero-art"><div className="sun"/><img src="https://images.unsplash.com/photo-1533130061792-64b345e4a833?auto=format&fit=crop&w=1000&q=90"/><div className="hero-tag">01 <span>/</span> 04</div><div className="hero-quote">« Créer, c'est<br/><b>laisser une trace.</b> »</div></div></section>
 <div className="section-head"><div><span className="kicker">LA SÉLECTION D'INFINI</span><h2>En ce moment</h2></div><button className="see-all" onClick={()=>go('discover')}>Voir tout <ArrowRight size={15}/></button></div>
 <section className="feature-grid"><div className="feature-card featured"><img src={tracks[0].cover}/><div className="shade"/><div className="feature-info"><span className="chip">À LA UNE</span><h3>Mokili</h3><p>Jérémie Kanda · Album</p><button className="round-play" onClick={()=>setPlaying(playing?.title===tracks[0].title?null:tracks[0])}>{playing?.title===tracks[0].title?<Pause size={18}/>:<Play size={18} fill="currentColor"/>}</button></div></div><div className="feature-card small-feature"><img src="https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=800&q=85"/><div className="shade"/><div className="feature-info"><span className="chip coral">PERFORMANCE</span><h3>Vibrations</h3><p>Live session · 18 min</p></div><button className="round-play play-float" onClick={()=>setPlaying(tracks[1])}><Play size={17} fill="currentColor"/></button></div><div className="feature-card small-feature"><img src="https://images.unsplash.com/photo-1561214115-f2f134cc4912?auto=format&fit=crop&w=800&q=85"/><div className="shade"/><div className="feature-info"><span className="chip blue">À DÉCOUVRIR</span><h3>Regards croisés</h3><p>Exposition numérique</p></div></div></section>
 <section className="row-section"><div className="section-head compact"><div><span className="kicker">POUR VOS OREILLES</span><h2>Les titres du moment</h2></div><button className="see-all" onClick={()=>go('music')}>Tout écouter <ArrowRight size={15}/></button></div><div className="track-list">{tracks.map((t,i)=><Track key={t.title} t={t} index={i} playing={playing} setPlaying={setPlaying} liked={liked} setLiked={setLiked}/>)}</div></section>
 <section className="row-section artists-row"><div className="section-head compact"><div><span className="kicker">NOUVELLES VOIX</span><h2>Artistes à suivre</h2></div><button className="see-all" onClick={()=>go('artists')}>Explorer <ArrowRight size={15}/></button></div><div className="artist-grid">{artists.map(a=><div className="artist-card" key={a.name} onClick={()=>go('artists')}><img src={a.img}/><div><b>{a.name}</b><span>{a.genre}</span></div><button><Plus size={16}/></button></div>)}</div></section>
 <section className="support-banner"><div><span className="kicker">NOTRE MISSION</span><h2>Votre écoute change<br/>une <em>histoire.</em></h2><p>Chaque écoute, chaque achat, chaque geste compte pour les artistes indépendants.</p></div><button className="light-btn" onClick={()=>go('store')}>Soutenir la création <ArrowRight size={16}/></button></section>
 </>}
function Track({t,index,playing,setPlaying,liked,setLiked}){let is=playing?.title===t.title;return <div className={is?'track playing':'track'}><span className="track-num">{is?<span className="equalizer">▮▮▮</span>:`0${index+1}`}</span><img src={t.cover}/><div className="track-title"><b>{t.title}</b><span>{t.artist}</span></div><span className="track-album">{t.album}</span><span className="track-plays">{t.plays}</span><span className="track-time">{t.time}</span><button className={liked.includes(t.title)?'heart liked':'heart'} onClick={()=>setLiked(liked.includes(t.title)?liked.filter(x=>x!==t.title):[...liked,t.title])}><Heart size={16} fill={liked.includes(t.title)?'currentColor':'none'}/></button><button className="play-small" onClick={()=>setPlaying(is?null:t)}>{is?<Pause size={15}/>:<Play size={15} fill="currentColor"/>}</button></div>}
 function Player({track,setPlaying}){return <div className="player"><div className="player-track"><img src={track.cover}/><div><b>{track.title}</b><span>{track.artist}</span></div><Heart size={16} className="player-heart"/></div><div className="player-controls"><button>⏮</button><button className="player-play" onClick={()=>setPlaying(null)}><Pause size={17} fill="currentColor"/></button><button>⏭</button><div className="progress"><span/><i/></div></div><div className="player-tools"><span>1:24 / {track.time}</span><Headphones size={17}/><span className="volume">━━●</span></div></div>}
 function Collection({page,go,playing,setPlaying,add}){let title=page==='discover'?'Tout commence par une découverte':page==='music'?'La musique en mouvement':page==='videos'?'Images, rythmes et récits':page==='performances'?'Le vivant, sans filtre':page==='artists'?'Celles et ceux qui créent':'La boutique des artistes';let sub=page==='artists'?'Des voix singulières, des univers à explorer.':'Explorez une sélection pensée pour vous faire ressentir, découvrir et soutenir.';return <div className="collection"><div className="collection-top"><div><span className="kicker">{page==='store'?'SOUTENIR DIRECTEMENT':'EXPLORER INFINI RECORD'}</span><h1>{title}</h1><p>{sub}</p></div><button className="filter-btn"><Compass size={16}/> Filtrer</button></div><div className="category-tabs"><button className="active">Tout</button><button>Nouveautés</button><button>Tendances</button><button>Afro-soul</button><button>Live</button><button>Prix</button></div>{page==='artists'?<div className="big-artist-grid">{artists.map((a,i)=><div className="big-artist" key={i}><img src={a.img}/><div><b>{a.name}</b><span>{a.genre}</span></div><button className="outline-btn" onClick={()=>go('artist')}>Voir le profil</button></div>)}</div>:page==='store'?<div className="product-grid">{products.concat(products[1]).map((p,i)=><div className="product" key={i}><div className="product-image"><img src={p.cover}/><button className="product-add" onClick={()=>add(p)}><Plus size={18}/></button></div><div className="product-meta"><div><b>{p.name}</b><span>{p.artist} · {p.type}</span></div><strong>{p.price}</strong></div></div>)}</div>:<><div className="collection-hero"><img src={page==='videos'? 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=1400&q=85':tracks[2].cover}/><div><span className="chip">CHOIX DE LA SEMAINE</span><h2>Les sons qui<br/><em>traversent les frontières</em></h2><button className="primary" onClick={()=>setPlaying(tracks[2])}>Écouter maintenant <Play size={15} fill="currentColor"/></button></div></div><div className="section-head compact"><div><span className="kicker">SÉLECTION POUR VOUS</span><h2>{page==='videos'?'À regarder maintenant':'Les incontournables'}</h2></div></div><div className="track-list">{tracks.concat(tracks[1]).map((t,i)=><Track key={i} t={t} index={i%4} playing={playing} setPlaying={setPlaying} liked={[]} setLiked={()=>{}}/>)}</div></>}</div>}
 function LibraryPage({go}){return <div className="library-page"><div className="collection-top"><div><span className="kicker">VOTRE ESPACE</span><h1>Ma bibliothèque</h1><p>Tout ce que vous aimez, au même endroit.</p></div><button className="primary" onClick={()=>go('discover')}>Ajouter du contenu <Plus size={16}/></button></div><div className="library-stats"><div><Headphones/><b>24</b><span>Titres sauvegardés</span></div><div><Download/><b>8</b><span>Achats disponibles</span></div><div><Heart/><b>12</b><span>Favoris</span></div></div><div className="section-head compact"><div><span className="kicker">RÉCEMMENT AJOUTÉS</span><h2>Votre collection musicale</h2></div></div><div className="track-list">{tracks.map((t,i)=><Track key={t.title} t={t} index={i} playing={null} setPlaying={()=>{}} liked={[]} setLiked={()=>{}}/>)}</div></div>}
 function Cart({cart,setCart,go}){return <div className="cart-page"><span className="kicker">VOTRE SÉLECTION</span><h1>Panier</h1>{cart.length===0?<div className="empty"><ShoppingBag size={42}/><h2>Votre panier est vide</h2><p>Les œuvres que vous ajoutez apparaîtront ici.</p><button className="primary" onClick={()=>go('store')}>Découvrir la boutique <ArrowRight size={16}/></button></div>:<div className="cart-layout"><div>{cart.map((p,i)=><div className="cart-item" key={i}><img src={p.cover}/><div><b>{p.name}</b><span>{p.artist} · {p.type}</span></div><strong>{p.price}</strong><button onClick={()=>setCart(cart.filter((_,x)=>x!==i))}><X size={18}/></button></div>)}</div><div className="summary"><span>Total</span><h2>{cart.reduce((a,p)=>a+parseFloat(p.price),0).toFixed(2).replace('.',',')} $</h2><button className="primary">Passer au paiement <ArrowRight size={16}/></button><small>Paiement sécurisé · Accès instantané</small></div></div>}</div>}
 function ArtistDashboard({go}){return <div className="dashboard"><div className="dash-top"><div><span className="kicker">ESPACE ARTISTE</span><h1>Bonjour, artiste.</h1><p>Voici ce qui se passe avec votre art.</p></div><button className="primary" onClick={()=>go('upload')}><Upload size={16}/> Publier une œuvre</button></div><div className="dash-cards"><div><DollarSign/><span>Revenus ce mois</span><b>1 284,50 $</b><small>↗ 18,4% <i>vs mois dernier</i></small></div><div><Headphones/><span>Écoutes</span><b>42 891</b><small>↗ 12,8% <i>vs mois dernier</i></small></div><div><ShoppingBag/><span>Ventes</span><b>186</b><small>↗ 8,2% <i>vs mois dernier</i></small></div><div><Users/><span>Abonnés</span><b>3 842</b><small>↗ 5,1% <i>vs mois dernier</i></small></div></div><div className="dash-grid"><div className="chart-card"><div className="card-head"><div><span className="kicker">PERFORMANCE</span><h2>Évolution des écoutes</h2></div><button>30 derniers jours⌄</button></div><div className="chart"><div className="chart-labels"><span>8k</span><span>6k</span><span>4k</span><span>2k</span><span>0</span></div><svg viewBox="0 0 720 220" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stopColor="#df6b43" stopOpacity=".3"/><stop offset="1" stopColor="#df6b43" stopOpacity="0"/></linearGradient></defs><path d="M0 190 C40 180 58 140 90 156 S140 180 175 130 S230 115 260 140 S310 94 350 112 S395 120 430 76 S480 95 515 62 S560 88 590 40 S640 58 680 27 S710 39 720 12 V220 H0Z" fill="url(#fill)"/><path d="M0 190 C40 180 58 140 90 156 S140 180 175 130 S230 115 260 140 S310 94 350 112 S395 120 430 76 S480 95 515 62 S560 88 590 40 S640 58 680 27 S710 39 720 12" fill="none" stroke="#df6b43" strokeWidth="3"/></svg><div className="chart-days"><span>01 août</span><span>08 août</span><span>15 août</span><span>22 août</span><span>28 août</span></div></div></div><div className="recent-card"><div className="card-head"><div><span className="kicker">ACTIVITÉ</span><h2>Dernières ventes</h2></div><button>Voir tout →</button></div>{tracks.slice(0,3).map((t,i)=><div className="sale" key={i}><img src={t.cover}/><div><b>{t.title}</b><span>Acheté par un fan</span></div><strong>+{i? '7,00':'12,00'} $</strong></div>)}</div></div></div>}
function SettingsPage(){
 const [saved,setSaved]=useState(false); const [prefs,setPrefs]=useState({name:'Junior M.',email:'junior@email.com',bio:'Je découvre et soutiens les talents africains.',notifications:true,public:true});
 const update=(key,value)=>{setSaved(false);setPrefs({...prefs,[key]:value});
 };
 return <div className="settings-page"><div className="collection-top"><div><span className="kicker">VOTRE COMPTE</span><h1>Paramètres</h1><p>Gérez votre profil et vos préférences.</p></div><button className="primary" onClick={()=>setSaved(true)}><Save size={16}/> Enregistrer</button></div>{saved&&<div className="success-message"><Check size={16}/> Vos paramètres ont été enregistrés.</div>}<div className="settings-grid"><section className="settings-card"><div className="settings-card-head"><div><span className="kicker">PROFIL</span><h2>Informations personnelles</h2></div><img src={artists[1].img} alt="Avatar"/></div><label>Nom complet<input value={prefs.name} onChange={e=>update('name',e.target.value)}/></label><label>Adresse email<input type="email" value={prefs.email} onChange={e=>update('email',e.target.value)}/></label><label>Bio<textarea value={prefs.bio} onChange={e=>update('bio',e.target.value)}/></label></section><section className="settings-card"><span className="kicker">PRÉFÉRENCES</span><h2>Notifications et visibilité</h2><div className="setting-row"><div><b>Nouveautés des artistes</b><span>Recevoir les sorties et recommandations.</span></div><button className={prefs.notifications?'toggle on':'toggle'} onClick={()=>update('notifications',!prefs.notifications)}><i/></button></div><div className="setting-row"><div><b>Profil public</b><span>Permettre aux autres membres de voir votre activité.</span></div><button className={prefs.public?'toggle on':'toggle'} onClick={()=>update('public',!prefs.public)}><i/></button></div><button className="danger-btn">Se déconnecter de tous les appareils</button></section></div></div>
}

function UploadPage({go}){
 const [type,setType]=useState('song'); const [title,setTitle]=useState(''); const [description,setDescription]=useState(''); const [price,setPrice]=useState('0'); const [file,setFile]=useState(''); const [cover,setCover]=useState(''); const [published,setPublished]=useState(false);
 const submit=e=>{e.preventDefault();setPublished(true)};
 if(published)return <div className="upload-page"><div className="success-panel"><Check size={42}/><span className="kicker">PUBLICATION ENREGISTRÉE</span><h1>Votre œuvre est en cours de validation.</h1><p>Notre équipe va vérifier votre contenu. Vous recevrez une notification dès sa mise en ligne.</p><div><button className="primary" onClick={()=>{setPublished(false);setTitle('');setFile('')}}>Publier une autre œuvre</button><button className="ghost" onClick={()=>go('artist')}>Retour au tableau de bord</button></div></div></div>;
 return <div className="upload-page"><div className="collection-top"><div><span className="kicker">ESPACE ARTISTE</span><h1>Publier une œuvre</h1><p>Partagez votre création avec la communauté Infini Record.</p></div><button className="ghost" onClick={()=>go('artist')}>Annuler</button></div><form className="upload-form" onSubmit={submit}><section className="settings-card"><span className="kicker">CONTENU</span><h2>Présentez votre création</h2><label>Type d’œuvre<select value={type} onChange={e=>setType(e.target.value)}><option value="song">Chanson</option><option value="album">Album</option><option value="video">Vidéo</option><option value="performance">Performance</option></select></label><label>Titre de l’œuvre<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ex. La lumière du fleuve"/></label><label>Description<textarea required value={description} onChange={e=>setDescription(e.target.value)} placeholder="Racontez l’histoire de cette œuvre..."/></label><div className="upload-fields"><label className="file-drop"><FileAudio size={24}/><b>{file||'Ajouter le fichier principal'}</b><span>MP3, WAV ou MP4 · 500 Mo maximum</span><input required type="file" accept="audio/*,video/*" onChange={e=>setFile(e.target.files[0]?.name||'')}/></label><label className="file-drop"><Image size={24}/><b>{cover||'Ajouter une pochette'}</b><span>JPG ou PNG · 2000 × 2000 px</span><input required type="file" accept="image/*" onChange={e=>setCover(e.target.files[0]?.name||'')}/></label></div></section><aside className="settings-card publish-card"><span className="kicker">COMMERCIALISATION</span><h2>Prix et accès</h2><label>Prix de vente<input type="number" min="0" step="0.5" value={price} onChange={e=>setPrice(e.target.value)}/></label><div className="price-note">{price==='0'?'Cette œuvre sera accessible gratuitement.':`Les fans paieront ${price} $ pour y accéder.`}</div><button className="primary publish-btn"><Upload size={16}/> Envoyer pour validation</button><small>En publiant, vous confirmez posséder les droits de cette œuvre.</small></aside></form></div>
}

 createRoot(document.getElementById('root')).render(<App/>);
